"""advisory jobs and audit

Revision ID: 0003_advisory
Revises: 0002_ingestion
Create Date: 2026-09-24 18:06:42.001363

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003_advisory"
down_revision: str | Sequence[str] | None = "0002_ingestion"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advisory_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("delivery_id", sa.String(length=100), nullable=False),
        sa.Column("task_index", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=60), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repository", sa.String(length=200), nullable=False),
        sa.Column("pull_number", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.BigInteger(), nullable=True),
        sa.Column("head_sha", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("delivery_id", "task_index"),
    )
    op.create_index(
        op.f("ix_advisory_jobs_repository"), "advisory_jobs", ["repository"], unique=False
    )
    op.create_index(op.f("ix_advisory_jobs_status"), "advisory_jobs", ["status"], unique=False)
    op.create_table(
        "verification_audit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repository", sa.String(length=200), nullable=False),
        sa.Column("pull_number", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.BigInteger(), nullable=False),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column("inputs_sha256", sa.String(length=64), nullable=False),
        sa.Column("pipeline_version", sa.String(length=60), nullable=False),
        sa.Column("verdict", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.String(length=10), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["advisory_jobs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_audit_repository"), "verification_audit", ["repository"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_audit_repository"), table_name="verification_audit")
    op.drop_table("verification_audit")
    op.drop_index(op.f("ix_advisory_jobs_status"), table_name="advisory_jobs")
    op.drop_index(op.f("ix_advisory_jobs_repository"), table_name="advisory_jobs")
    op.drop_table("advisory_jobs")
    # ### end Alembic commands ###
