"""staged enforcement

Revision ID: 0004_enforcement
Revises: 0003_advisory
Create Date: 2026-09-24 18:51:57.848484

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004_enforcement"
down_revision: str | Sequence[str] | None = "0003_advisory"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository_policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repository", sa.String(length=200), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("enforced_categories", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "stage_since",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id", "repository"),
    )
    op.create_table(
        "repository_policy_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repository", sa.String(length=200), nullable=False),
        sa.Column("from_stage", sa.String(length=20), nullable=True),
        sa.Column("to_stage", sa.String(length=20), nullable=False),
        sa.Column("enforced_categories", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repository_policy_changes_repository"),
        "repository_policy_changes",
        ["repository"],
        unique=False,
    )
    op.create_table(
        "review_confirmations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("repository", sa.String(length=200), nullable=False),
        sa.Column("pull_number", sa.Integer(), nullable=False),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column("reviewer", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("installation_id", "repository", "head_sha", "reviewer"),
    )
    op.create_index(
        op.f("ix_review_confirmations_repository"),
        "review_confirmations",
        ["repository"],
        unique=False,
    )
    op.add_column("advisory_jobs", sa.Column("actor", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("advisory_jobs", "actor")
    op.drop_index(op.f("ix_review_confirmations_repository"), table_name="review_confirmations")
    op.drop_table("review_confirmations")
    op.drop_index(
        op.f("ix_repository_policy_changes_repository"), table_name="repository_policy_changes"
    )
    op.drop_table("repository_policy_changes")
    op.drop_table("repository_policies")
    # ### end Alembic commands ###
