"""audit review case

Revision ID: 0005_dashboard
Revises: 0004_enforcement
Create Date: 2026-09-24 19:09:19.188614

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005_dashboard"
down_revision: str | Sequence[str] | None = "0004_enforcement"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification_audit",
        sa.Column("review_case", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("verification_audit", "review_case")
    # ### end Alembic commands ###
